### ISSUE TITLE
运行报错—— “ Business error. Code: InvalidVSwitchId.NotExist, Message: vSwitch not exists”

### ISSUE THREAD

**Issue by tinyhuang** [smaugx/aliyun_spot#1]
仅仅修改了 access_id, access_secret, ssh_key_file, key_pair_name 以及 spot_price_limit (0.05)

运行后报错如下。请大神看看是哪的问题。多谢。

> james@dockerhost:/mnt/MySeafile/AliYunSpot/aliyun_spot$ python run_aliyunspot.py -c
will create and run aliyun spot instance, please wait...
Fail. Business error. Code: InvalidVSwitchId.NotExist, Message: vSwitch not exists
Traceback (most recent call last):
  File "run_aliyunspot.py", line 255, in <module>
    create_aliyun_spot()
  File "run_aliyunspot.py", line 196, in create_aliyun_spot
    for instance in data['Instances']['Instance']:
TypeError: 'NoneType' object is not subscriptable

**Comment by tinyhuang** [comment]
搞定了。
大神的代码里面用的是自己账号下的vswitch，另外security grop也要根据自己的情况定义。简单修改了一下就没问题了。

感谢赐教。
